name: Unit Test

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: ./docker.sh build
      - name: Run tests in Container
        run: |
          ./docker.sh up
          ./docker.sh test
